version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:1.0
    ports:
      - "${API_PORT:-8080}:8080"
  
  api_test:
    build: ./api-testing
    tty: true
    volumes:
      - ./api-test-report:/etc/newman/newman

  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile_sonar
  
  check:
    build:
      context: .
      dockerfile: Dockerfile_check
    volumes:
      - ./check-report:/check_report

  jmeter:
    build:
      context: ./jmeter
      dockerfile: Dockerfile
    volumes:
      - ./jmeter/demo2.jmx:/test.jmx
      - ./jmeter-report:/jmeter_report
    command: -n -t /test.jmx -l /jmeter_report/report.jtl -e -o /jmeter_report